# Generated by Django 3.1.7 on 2021-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfor',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfor',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
